spring:
  profiles:
    active: dev

# Logging
logging:
  level:
    root: INFO

---
spring:
  profiles: staging
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    # DONT use below in production! Manually maintenance(sql & review & patch) is the right way.
    hibernate:
      ddl-auto: update

---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Only use ddl-auto in testing or dev, as it automatically changes schema in db, which should not be allowed by product DBAs.
      # "validate" means it only validate schema changes and no affect on db;
      # "create" means it destroys previous data & create schema;
      # "update" means only update schema not touching data(but still! dont use it in product);
      # "create-drop" means destroy previous data and create schema, and drop table & data when application closes.
      # ddl-auto= validate | create | update | create-drop.
      ddl-auto: create-drop
    show-sql: true